<a href="https://colab.research.google.com/github/falling90/AI_Pre-course/blob/main/3_%EA%B8%B0%EC%B4%88_%EC%88%98%ED%95%99_%ED%95%9C%EA%B1%B8%EC%9D%8C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1) Numpy / 벡터 & 행렬
### 　A. Numerical Python - Numpy

In [ ]:
import numpy as np

test_array = np.array(["1", "4", 5, 8], float)
print(test_array)
print(type(test_array[3]))

[1. 4. 5. 8.]
<class 'numpy.float64'>


In [ ]:
test_array = np.array([1, 4, 5, "8"], np.float32) #	String	Type의 데이터를 입력해도
print(test_array)
print(type(test_array[3]))	 	 	 #	Float	Type으로 자동 형변환을 실시
print(test_array.dtype) #	Array(배열)	전체의 데이터 Type을 반환함
print(test_array.shape) #	Array(배열)	의 shape을 반환함

[1. 4. 5. 8.]
<class 'numpy.float32'>
float32
(4,)


In [ ]:
tensor = [[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]],
          [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]]

print(np.array(tensor, int).shape)
print(np.array(tensor, int).ndim)
print(np.array(tensor, int).size)

(2, 3, 4)
3
24


> Reshape : Array의 shape의 크기를 변경함 (element의 갯수는 동일)  
> flatten : 다차원 Array를 1차원 Array 로 변환

In [ ]:
tensor = [[1, 2, 3, 4], [1, 2, 3, 4]]

print(np.array(tensor, int))
print("-----------------------")
print(np.array(tensor).reshape(2, 2, 2))
print("-----------------------")
print(np.array(tensor).reshape(8))
print("-----------------------")
print(np.array(tensor).reshape(-1, 2))
print("-----------------------")
print(np.array(tensor).reshape(4, -1, 2))


print("-----------------------")
print(np.array(tensor).flatten())

[[1 2 3 4]
 [1 2 3 4]]
-----------------------
[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]
-----------------------
[1 2 3 4 1 2 3 4]
-----------------------
[[1 2]
 [3 4]
 [1 2]
 [3 4]]
-----------------------
[[[1 2]]

 [[3 4]]

 [[1 2]]

 [[3 4]]]
-----------------------
[1 2 3 4 1 2 3 4]


> Slicing : Array의 원하는 Data만 추출할 때 사용

In [ ]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
print(a[:,2:])    # 전체 Row의 2열 이상
print("-----------------------")
print(a[1,1:3])   # 1 Row의 1열 ~ 2열
print("-----------------------")
print(a[1:3])     # 1 Row ~ 2Row의 전체

[[ 3  4  5]
 [ 8  9 10]]
-----------------------
[7 8]
-----------------------
[[ 6  7  8  9 10]]


> Arange : Array의 범위를 지정하여, 값의 List를 생성하는 명령어  
> zeros : Array를 생성하는데 0으로 초기화  
> ones : Array를 생성하는데 0으로 초기화  
> empty : Array를 생성하는데 메모리만 잡아줌 (이상한 값(Garbage)이 나올 수 있음.)

In [ ]:
print(np.arange(30))
print("-----------------------")
print(np.arange(30).reshape(-1, 5))
print("-----------------------")
print(np.arange(3, 5, 0.5))
print("-----------------------")
print(np.arange(30))
print("-----------------------")
print(np.zeros(shape=(10,), dtype=np.int8))
print("-----------------------")
print(np.zeros((2, 5)))
print("-----------------------")
print(np.ones(shape=(10,), dtype=np.int8))
print("-----------------------")
print(np.ones((2, 5)))
print("-----------------------")
print(np.empty(shape=(10,), dtype=np.int8))
print("-----------------------")
print(np.empty((3, 5)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
-----------------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
-----------------------
[3.  3.5 4.  4.5]
-----------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
-----------------------
[0 0 0 0 0 0 0 0 0 0]
-----------------------
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
-----------------------
[1 1 1 1 1 1 1 1 1 1]
-----------------------
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
-----------------------
[1 1 1 1 1 1 1 1 1 1]
-----------------------
[[0.00000000e+000 1.03977794e-312 1.01855798e-312 9.54898106e-313
  1.01855798e-312]
 [1.03977794e-312 1.23075756e-312 1.18831764e-312 1.01855798e-312
  9.76118064e-313]
 [1.08221785e-312 1.03977794e-312 1.03977794e-312 2.22809558e-312
  2.14321575e-312]]


> something_like : 배열의 크기만큼 1, 0 또는 empty array를 반환

In [ ]:
test_matrix = np.arange(30).reshape(5, 6)
print(np.ones_like(test_matrix))
print("-----------------------")
print(np.zeros_like(test_matrix))
print("-----------------------")
print(np.empty_like(test_matrix))   # 메모리에 이전 데이터가 남아서 나오는 것

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
-----------------------
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
-----------------------
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


> identity : 단위행렬  
> eye : 대각선이 1 인 행렬  
> diag : 대각 행렬의 값만 추출  
> random sampling : 데이터 분포에 따른 sampling으로 array 생성

In [ ]:
print(np.identity(n=3, dtype=np.int8))
print("-----------------------")
print(np.eye(N=3, M=5, dtype=np.int8))    # N = row, M = column
print(np.eye(3))
print(np.eye(3, 5, k=2))                  # k = start index
print("-----------------------")
test_matrix = np.arange(9).reshape(3, 3)
print(np.diag(test_matrix))
print(np.diag(test_matrix, k=1))          # k = start index
print("-----------------------")
print(np.random.uniform(0, 1, 10).reshape(2, 5))  # 균등분포
print(np.random.normal(0, 1, 10).reshape(2, 5))   # 정규분포
print("-----------------------")
print("-----------------------")

[[1 0 0]
 [0 1 0]
 [0 0 1]]
-----------------------
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
-----------------------
[0 4 8]
[1 5]
-----------------------
[[0.97671224 0.21682674 0.05484679 0.42893581 0.77431709]
 [0.54179584 0.10488044 0.16668692 0.06604285 0.44988771]]
[[-0.83075038 -2.38584941 -0.37765315 -0.86225583  0.33888118]
 [-0.09918727  0.2971321   0.27273852  0.71839908 -1.18438599]]
-----------------------
-----------------------


> axis : 모든 operation function 을 실행할 때, 기준이 되는 dimension 축

In [ ]:
test_array = np.arange(1, 13).reshape(3, 4)
print(test_array)
print("-----------------------")
print(test_array.sum(axis=1))
print("-----------------------")
print(test_array.sum(axis=0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-----------------------
[10 26 42]
-----------------------
[15 18 21 24]


> concatenate : Numpy array를 합치는 함수

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.vstack((a, b)))
print("-----------------------")
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
print(np.hstack((a, b)))
print("-----------------------")
print(np.concatenate((a, b), axis=0))
print(np.concatenate((a, b), axis=1))

[[1 2 3]
 [4 5 6]]
-----------------------
[[1 4]
 [2 5]
 [3 6]]
-----------------------
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 4]
 [2 5]
 [3 6]]


> Numpy Performance  
　-. 속도 : for loop < list comprehension < numpy

In [ ]:
def sclar_vector_product(scalar, vector):
  result = []
  for value in vector:
    result.append(scalar * value)
  return result 

iternation_max = 100000000

vector = list(range(iternation_max))
scalar = 2

%timeit sclar_vector_product(scalar, vector) # for loop을 이용한 성능
%timeit [scalar * value for value in range(iternation_max)] # list comprehension을 이용한 성능
%timeit np.arange(iternation_max) * scalar # numpy를 이용한 성능

1 loop, best of 5: 15.1 s per loop
1 loop, best of 5: 13.2 s per loop
1 loop, best of 5: 327 ms per loop


> All & Any

In [ ]:
a = np.arange(10)

print(a > 5)
print("-----------------------")
print(np.any(a > 5))    # any = 하나라도 조건에 만족하면 True
print(np.any(a < 0))
print("-----------------------")
print(np.all(a > 5))
print(np.all(a < 10))   # all = 모두가 조건에 만족하면 True

[False False False False False False  True  True  True  True]
-----------------------
True
False
-----------------------
False
True


> np.where : where(condition, TRUE, FALSE)

In [ ]:
a = np.array([1, 3, 0], float)
print(np.where(a > 0, 3, 6))

a = np.arange(10)
print(np.where(a > 5))    #Index 값 반환

a = np.array([1, np.NaN, np.Inf], float)
print(np.isnan(a))
print(np.isfinite(a))

[3 3 6]
(array([6, 7, 8, 9]),)
[False  True False]
[ True False False]


> argmax & argmin : array 內 최대값 또는 최소값의 index를 반환 (axis 기반 반환)

In [ ]:
a = np.array([1, 2, 4, 5, 8, 78, 23, 3])
print(np.argmax(a))
print(np.argmin(a))

5
0


> boolean index : 특정 조건에 따른 값을 배열 형태로 추출

In [ ]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
print(test_array > 3)

print(test_array[test_array > 3])

condition = test_array > 3
print(test_array[condition])

[False  True False False False  True  True  True]
[4. 8. 9. 7.]
[4. 8. 9. 7.]


In [ ]:
A = np.array([
[12, 13, 14, 12, 16, 14, 11, 10,  9],
[11, 14, 12, 15, 15, 16, 10, 12, 11],
[10, 12, 12, 15, 14, 16, 10, 12, 12],
[ 9, 11, 16, 15, 14, 16, 15, 12, 10],
[12, 11, 16, 14, 10, 12, 16, 12, 13],
[10, 15, 16, 14, 14, 14, 16, 15, 12],
[13, 17, 14, 10, 14, 11, 14, 15, 10],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 17, 19, 16, 17, 18, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 12, 14, 11, 12, 14, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11]])
B = A < 15

print(B)
print("-----------------------")
print(B.astype(np.int))

[[ True  True  True  True False  True  True  True  True]
 [ True  True  True False False False  True  True  True]
 [ True  True  True False  True False  True  True  True]
 [ True  True False False  True False False  True  True]
 [ True  True False  True  True  True False  True  True]
 [ True False False  True  True  True False False  True]
 [ True False  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True False  True]
 [ True False False False False False False False  True]
 [ True False  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True False  True]
 [ True False  True  True  True  True  True False  True]]
-----------------------
[[1 1 1 1 0 1 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 1 0 1 1 1]
 [1 1 0 0 1 0 0 1 1]
 [1 1 0 1 1 1 0 1 1]
 [1 0 0 1 1 1 0

> fancy index : numpy는 array를 index value로 사용해서 값을 추출하는 방법

In [ ]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
print(a[b])
print(a.take(b))

[2. 2. 4. 8. 6. 4.]
[2. 2. 4. 8. 6. 4.]


In [ ]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c] # b를 row index, c를 column index로 변환하여 표시함

array([ 1.,  4., 16., 16.,  4.])

##1) Numpy / 벡터 & 행렬
### 　B. 벡터가 뭐에요?

> Vector  
　-. 공간에서의 한 점을 나타냄  
　-. 원점으로부터 상대적 위치를 표현  
　-. 숫자를 곱해주면 길이만 변함  
　-. 숫자를 원소로 가지는 리스트(list) 또는 배열(array)  

>■ 노름(norm) : 원점에서부터의 거리  
　-. L1 Norm : 각 성분 변화량의 절대값의 합  
　-. L2 Norm : 피타고라스 정리를 이용해 유클리드 거리를 계산  

>◎ 노름의 종류에 따라 기하학적 성질이 달라짐 (기계학습의 목적에 따라 설정)  
　-. L1 Norm : Robust 학습, Lasso 회귀  
　-. L2 Norm : Laplace 근사, Ridge 회귀  

> 두 벡터 사이의 각도 구해보기 (단, L2 Norm 에서만 가능)  
　-. 제 2 코사인 법칙 이용  
　　→ 두 벡터간의 각도 : arccos( inner(x, y) / L2(x) * L2(y) )  
　　→ 내적(inner) : 정사영된 벡터의 길이  
　　　> 내적은 두 벡터의 유사도(similarity)를 측정하는데 사용 가능  

##1) Numpy / 벡터 & 행렬
### 　C. 행렬이 뭐에요?

> 행렬(matrix) : 벡터를 원소로 가지는 2차원 배열  
　※ numpy 에서는 행(row)이 기본 단위이다!!

> 전치행렬(transpose matrix) : 행과 열을 바꾼 행렬 (우측 상단에 T 표시)  
　-. Xij -> Xji

> 행렬곱 : i번째 행벡터와 j번째 열벡터 사이의 내적을 성분으로 가지는 행렬을 계산  
　-. numpy 에서는 @ 연산을 사용함

>※ 수학과 다르게 numpy의 inner 함수는 i번째 "행벡터"와 j번째 "행벡터" 사이의 내적을 함!!  
　-. inner(x, y) 를 쓰면 수학적으로는 x * yT 를 계산한다고 보면 됨

In [8]:
import numpy as np

# x = 4 * 3
x = np.array([[1, 2, 3],
              [2, 3, 4],
              [4, 5, 6],
              [6, 7, 8]])

# y = 2 * 3
y = np.array([[1, 2, 3],
              [2, 3, 4]])

print(x.shape)
print(y.shape)
print()
print(np.inner(x, y))

(4, 3)
(2, 3)

[[14 20]
 [20 29]
 [32 47]
 [44 65]]


> 역행렬(inverse matrix) : 어떤 행렬 A의 연산을 거꾸로 되돌리는 행렬  
　-. 조건 : 행과 열의 숫자가 같고, 행렬식(determinant)이 0이 아닌 경우에만 계산 가능  
　-. AA-1 = A-1A = I (항등행렬)

In [11]:
x = np.array([[1, -2, 3],
              [7, 5, 0],
              [-2, -1, 2]])

print(np.linalg.inv(x))
print()
print(x @ np.linalg.inv(x))

[[ 0.21276596  0.0212766  -0.31914894]
 [-0.29787234  0.17021277  0.44680851]
 [ 0.06382979  0.10638298  0.40425532]]

[[ 1.00000000e+00 -1.38777878e-17  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00 -5.55111512e-17]
 [-2.77555756e-17  0.00000000e+00  1.00000000e+00]]


>※ 역행렬을 계산할 수 없다면 "유사역행렬(pseudo-inverse)" 또는 "무어-펜로즈(Moore-Penrose)" 역행렬 A+를 이용한다.  
　-. 행과 열의 개수가 같지 않아도 계산 가능!  
　-. 조건 1) 행이 열보다 더 클 경우 (n >= m)  
　　→ A+ = (AT * A)-1 * AT  
　-. 조건 2) 열이 행보다 더 클 경우 (n <= m)  
　　→ A+ = AT * (A * AT)-1  
※ 곱셈의 순서가 매우 중요!!!

In [13]:
y = np.array([[0, 1],
              [1, -1],
              [-2, 1]])
print(np.linalg.pinv(y))
print()
print(np.linalg.pinv(y) @ y)

[[ 5.00000000e-01  4.09730229e-17 -5.00000000e-01]
 [ 8.33333333e-01 -3.33333333e-01 -1.66666667e-01]]

[[ 1.00000000e+00 -2.22044605e-16]
 [ 5.55111512e-17  1.00000000e+00]]


> 선형회귀 분석 : 유사 역행렬을 이용하여 찾을 수 있다.
　-. 데이터(X)가 더 많기 때문에 행의 개수(n)가 열의 개수(m)보다 많다.

In [ ]:
# #### Scikit Learn 을 활용한 회귀분석 (y절편 자동으로 고려해준다.)
# from sklearn.linear_model import LinearRegression
# model = LinearRegression()
# model.fit(X, y)
# y_test = model.predict(x_test)

# #### Moore-Penrose 역행렬 (y절편 직접 고려해줘야 함.)
# X_ = np.array(np.append(x, [1]) for x in X)   # intercept 항 추가
# beta = np.linalg.pinv(X_) @ y
# y_test = np.append(x, [1]) @ beta

##2) 경사하강법
### 　A. 경사하강법(순한맛)

> 미분(Differentiation) : 변수의 움직임에 따름 함수값의 변화량 (접선의 기울기)

In [2]:
# sympy를 이용하여 미분을 바로 구할 수 있다.

import sympy as sym
from sympy.abc import x

print(sym.diff(sym.poly(x**2 + 2*x + 3), x))

Poly(2*x + 2, x, domain='ZZ')


> 경사상승법(Gradient ascent) : 함수의 극대값의 위치를 구할 때 사용 (미분 값을 더한다.)  
> 경사하강법(Gradient descent) : 함수의 극소값의 위치를 구할 때 사용 (미분 값을 빼준다.)

> 벡터가 입력인 다변수 함수의 경우 편미분(partial differentiation)을 사용  
> 각 변수 별로 편미분을 계산한 그레디언트(gradient) 벡터를 이용하여 경사하강/상승법에 사용할 수 있다.

##2) 경사하강법
### 　B. 경사하강법(매운맛)

In [10]:
import numpy as np

X = np.array([[1, 1], [1, 2], [2, 2],[2, 3]])
y = np.dot(X, np.array([1, 2])) + 3

beta_gd = [10.1, 15.1, -6.5]
X_ = np.array([np.append(x, [1]) for x in X])

for t in range(5000):
  error = y - X_ @ beta_gd
  # error = error / np.linalg.norm(error)
  grad = - np.transpose(X_) @ error
  beta_gd = beta_gd - 0.01 * grad

print(beta_gd)

[1.00000367 1.99999949 2.99999516]


> 확률적 경사하강법(stochastic gradient descent) : 데이터 일부를 활용하여 업데이트  
> 볼록이 아닌(non-convex) 목적식은 SGD를 통해 최적화 할 수 있다.  
> SGD는 데이터 일부만 활용하기 때문에 연산자원을 좀 더 효율적으로 활용할 수 있다.